export enum MeActionTypes {
  CHANGE_THEME = 'ME.CHANGE_THEME',
  CHANGE_THEME_REQUEST = 'ME.CHANGE_THEME_REQUEST',
  CHANGE_THEME_SUCCESS = 'ME.CHANGE_THEME_SUCCESS',
  CHANGE_THEME_ERROR = 'ME.CHANGE_THEME_ERROR',
}
